---
name: Linting

on: [push, pull_request]

jobs:
  Black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable

  Flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install flake8
      - run: flake8 openmaps_auth

  Prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Prettier
        run: npm install prettier
      - name: Run Prettier
        run: npx prettier .
      - name: Run Prettier (check)
        continue-on-error: true
        run: npx prettier --check .
